SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `LOCADORA` DEFAULT CHARACTER SET utf8 ;

USE `LOCADORA` ;

-- Table `LOCADORA`.`CLIENTE`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `CPFCLIENTE` CHAR(11) NOT NULL,
  `NOMECLIENTE` VARCHAR(100) NOT NULL,
  `DATANASCIMENTO` DATE NOT NULL,
  `EMAILCLIENTE` VARCHAR(100) NOT NULL,
  `TELCLIENTE` VARCHAR(17) NOT NULL,
  `DATACADASTRO` DATE NOT NULL,
  PRIMARY KEY (`idCLIENTE`),
  UNIQUE INDEX `CPFCLIENTE_UNIQUE` (`CPFCLIENTE` ASC) VISIBLE)
ENGINE = InnoDB;


-- Table `LOCADORA`.`ESTADO`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`ESTADO` (
  `idESTADO` INT NOT NULL,
  `NOMEESTADO` VARCHAR(50) NOT NULL,
  `UFESTADO` CHAR(2) NOT NULL,
  PRIMARY KEY (`idESTADO`))
ENGINE = InnoDB;


-- Table `LOCADORA`.`CIDADE`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`CIDADE` (
  `idCIDADE` INT NOT NULL,
  `ESTADO_idESTADO` INT NOT NULL,
  `NOMECIDADE` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idCIDADE`),
  INDEX `fk_CIDADE_ESTADO_idx` (`ESTADO_idESTADO` ASC) VISIBLE,
  CONSTRAINT `fk_CIDADE_ESTADO`
    FOREIGN KEY (`ESTADO_idESTADO`)
    REFERENCES `LOCADORA`.`ESTADO` (`idESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Table `LOCADORA`.`FILIAL`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`FILIAL` (
  `idFILIAL` INT NOT NULL,
  `FILIALCIDADE` INT NOT NULL,
  `NOMEFILIAL` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idFILIAL`),
  INDEX `fk_FILIAL_CIDADE1_idx` (`FILIALCIDADE` ASC) VISIBLE,
  CONSTRAINT `fk_FILIAL_CIDADE1`
    FOREIGN KEY (`FILIALCIDADE`)
    REFERENCES `LOCADORA`.`CIDADE` (`idCIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Table `LOCADORA`.`FUNCIONARIO`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`FUNCIONARIO` (
  `idFUNCIONARIO` INT NOT NULL,
  `idFILIAL` INT NOT NULL,
  `CPFFUNC` CHAR(11) NOT NULL,
  `NOMEFUNC` VARCHAR(100) NOT NULL,
  `EMAILFUNC` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idFUNCIONARIO`),
  UNIQUE INDEX `CPFFUNC_UNIQUE` (`CPFFUNC` ASC) VISIBLE,
  INDEX `fk_FUNCIONARIO_FILIAL1_idx` (`idFILIAL` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIO_FILIAL1`
    FOREIGN KEY (`idFILIAL`)
    REFERENCES `LOCADORA`.`FILIAL` (`idFILIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Table `LOCADORA`.`CATEGORIA`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`CATEGORIA` (
  `idCATEGORIA` INT NOT NULL,
  `NOMECATEGORIA` VARCHAR(100) NOT NULL,
  `DESCCATEGORIA` VARCHAR(200) NOT NULL,
  `VALORDIARIA` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idCATEGORIA`))
ENGINE = InnoDB;


-- Table `LOCADORA`.`MARCA`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`MARCA` (
  `idMARCA` INT NOT NULL,
  `NOMEMARCA` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMARCA`))
ENGINE = InnoDB;


-- Table `LOCADORA`.`MODELO`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`MODELO` (
  `idMODELO` INT NOT NULL,
  `NOMEMODELO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idMODELO`))
ENGINE = InnoDB;


-- Table `LOCADORA`.`VEICULO`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`VEICULO` (
  `idVEICULO` INT NOT NULL,
  `PLACA` CHAR(7) NOT NULL,
  `RENAVAM` VARCHAR(11) NOT NULL,
  `ANOVEICULO` VARCHAR(45) NOT NULL,
  `STATUSVEICULO` VARCHAR(45) NOT NULL,
  `IDFILIAL` INT NOT NULL,
  `IDCATEGORIA` INT NOT NULL,
  `IDMARCA` INT NOT NULL,
  `IDMODELO` INT NOT NULL,
  PRIMARY KEY (`idVEICULO`),
  UNIQUE INDEX `PLACA_UNIQUE` (`PLACA` ASC) VISIBLE,
  UNIQUE INDEX `RENAVAM_UNIQUE` (`RENAVAM` ASC) VISIBLE,
  INDEX `fk_VEICULO_FILIAL1_idx` (`IDFILIAL` ASC) VISIBLE,
  INDEX `fk_VEICULO_CATEGORIA1_idx` (`IDCATEGORIA` ASC) VISIBLE,
  INDEX `fk_VEICULO_MARCA1_idx` (`IDMARCA` ASC) VISIBLE,
  INDEX `fk_VEICULO_MODELO1_idx` (`IDMODELO` ASC) VISIBLE,
  CONSTRAINT `fk_VEICULO_FILIAL1`
    FOREIGN KEY (`IDFILIAL`)
    REFERENCES `LOCADORA`.`FILIAL` (`idFILIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULO_CATEGORIA1`
    FOREIGN KEY (`IDCATEGORIA`)
    REFERENCES `LOCADORA`.`CATEGORIA` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULO_MARCA1`
    FOREIGN KEY (`IDMARCA`)
    REFERENCES `LOCADORA`.`MARCA` (`idMARCA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VEICULO_MODELO1`
    FOREIGN KEY (`IDMODELO`)
    REFERENCES `LOCADORA`.`MODELO` (`idMODELO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Table `LOCADORA`.`RESERVA`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`RESERVA` (
  `idRESERVA` INT NOT NULL,
  `IDCLIENTE` INT NOT NULL,
  `IDVEICULO` INT NOT NULL,
  `IDFILIALRETIRADA` INT NOT NULL,
  `IDFILIALDEV` INT NOT NULL,
  `DATAINICIORESERVA` DATE NOT NULL,
  `DATAPREVFIMRESERVA` DATE NOT NULL,
  `STATUSRESERVA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRESERVA`, `IDCLIENTE`, `IDVEICULO`),
  INDEX `fk_RESERVA_CLIENTE1_idx` (`IDCLIENTE` ASC) VISIBLE,
  INDEX `fk_RESERVA_VEICULO1_idx` (`IDVEICULO` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVA_CLIENTE1`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `LOCADORA`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESERVA_VEICULO1`
    FOREIGN KEY (`IDVEICULO`)
    REFERENCES `LOCADORA`.`VEICULO` (`idVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Table `LOCADORA`.`LOCACAO`
CREATE TABLE IF NOT EXISTS `LOCADORA`.`LOCACAO` (
  `IDLOCACAO` INT NOT NULL,
  `DATARETIRADA` DATE NOT NULL,
  `KMRETIRADA` INT NOT NULL,
  `IDFILIALDEV` INT NOT NULL,
  `DATADEVOLUCAO` DATE NOT NULL,
  `KMDEVOLUCAO` INT NOT NULL,
  `VALORDIARIA` DECIMAL(10,2) NOT NULL,
  `TAXAS` DECIMAL(10,2) NOT NULL,
  `MULTA` DECIMAL(10,2) NOT NULL,
  `VALORFINAL` DECIMAL(10,2) NOT NULL,
  `IDRESERVA` INT NOT NULL,
  `IDCLIENTE` INT NOT NULL,
  `IDVEICULO` INT NOT NULL,
  `IDFUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`IDLOCACAO`, `IDRESERVA`, `IDCLIENTE`, `IDVEICULO`),
  INDEX `fk_LOCACAO_RESERVA1_idx` (`IDRESERVA` ASC) VISIBLE,
  INDEX `fk_LOCACAO_CLIENTE1_idx` (`IDCLIENTE` ASC) VISIBLE,
  INDEX `fk_LOCACAO_VEICULO1_idx` (`IDVEICULO` ASC) VISIBLE,
  INDEX `fk_LOCACAO_FUNCIONARIO1_idx` (`IDFUNCIONARIO` ASC) VISIBLE,
  CONSTRAINT `fk_LOCACAO_RESERVA1`
    FOREIGN KEY (`IDRESERVA`)
    REFERENCES `LOCADORA`.`RESERVA` (`idRESERVA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCACAO_CLIENTE1`
    FOREIGN KEY (`IDCLIENTE`)
    REFERENCES `LOCADORA`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCACAO_VEICULO1`
    FOREIGN KEY (`IDVEICULO`)
    REFERENCES `LOCADORA`.`VEICULO` (`idVEICULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCACAO_FUNCIONARIO1`
    FOREIGN KEY (`IDFUNCIONARIO`)
    REFERENCES `LOCADORA`.`FUNCIONARIO` (`idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- Percebi que para deixar a descricao de STATUS VEICULO completa, é mais integro adicionar uma tabela status
CREATE TABLE `LOCADORA`.`STATUSVEICULO` (
  `idSTATUS` INT NOT NULL,
  `NOME_STATUS` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSTATUS`)
);




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


